services:
  website:
    image: rachartier/golf-cart-tracker-website
    container_name: golf-cart-tracker-website
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - API_URL=http://api
      - API_PORT=8000
    networks:
      - golf-network

  api:
    image: rachartier/golf-cart-tracker-api
    container_name: golf-cart-tracker-api
    restart: always
    ports:
      - "8000:8000"
    networks:
      - golf-network

networks:
  golf-network:
    driver: bridge
